export const INDUSTRY_TYPES = [
  { label: "Accounting", value: "Accounting" },
  { label: "Advertising", value: "Advertising" },
  { label: "Aerospace", value: "Aerospace" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Automotive", value: "Automotive" },
  { label: "Banking", value: "Banking" },
  { label: "Biotechnology", value: "Biotechnology" },
  { label: "Chemicals", value: "Chemicals" },
  { label: "Construction", value: "Construction" },
  { label: "Consumer Goods", value: "Consumer Goods" },
  { label: "Education", value: "Education" },
  { label: "Energy", value: "Energy" },
  { label: "Engineering", value: "Engineering" },
  { label: "Entertainment", value: "Entertainment" },
  { label: "Environmental Services", value: "Environmental Services" },
  { label: "Fashion", value: "Fashion" },
  { label: "Finance", value: "Finance" },
  { label: "Food & Beverage", value: "Food & Beverage" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Hospitality", value: "Hospitality" },
  { label: "Information Technology", value: "Information Technology" },
  { label: "Insurance", value: "Insurance" },
  { label: "Legal Services", value: "Legal Services" },
  { label: "Logistics & Transportation", value: "Logistics & Transportation" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Marketing", value: "Marketing" },
  { label: "Media & Communications", value: "Media & Communications" },
  { label: "Mining", value: "Mining" },
  { label: "Pharmaceuticals", value: "Pharmaceuticals" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Retail", value: "Retail" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Video Games", value: "Video Games" },
  { label: "Other", value: "Other" },
];

// lib/constants.ts
export const CURRENCY_TYPE = [
  { label: "USD - US Dollar ($)", value: "USD" },
  { label: "CAD - Canadian Dollar (CA$)", value: "CAD" },
  { label: "GBP - British Pound (£)", value: "GBP" },
  { label: "EUR - Euro (€)", value: "EUR" },
  { label: "AUD - Australian Dollar (A$)", value: "AUD" },
  { label: "JPY - Japanese Yen (¥)", value: "JPY" },
  { label: "CNY - Chinese Yuan (¥)", value: "CNY" },
  { label: "INR - Indian Rupee (₹)", value: "INR" },
  { label: "CHF - Swiss Franc (CHF)", value: "CHF" },
  { label: "NZD - New Zealand Dollar (NZ$)", value: "NZD" },
  { label: "SGD - Singapore Dollar (S$)", value: "SGD" },
  { label: "MXN - Mexican Peso (MX$)", value: "MXN" },
  { label: "BRL - Brazilian Real (R$)", value: "BRL" },
  { label: "ZAR - South African Rand (R)", value: "ZAR" },
  { label: "KRW - South Korean Won (₩)", value: "KRW" },
  { label: "Other", value: "Other" },
];

