import {
  Building2,
  User,
  Users,
  Palette,
  UserCheck,
  FileText,
  DollarSign,
  FileDigit,
  File,
  Mail,
} from "lucide-react";
// industry
export const INDUSTRY_TYPES = [
  { label: "Accounting", value: "Accounting" },
  { label: "Advertising", value: "Advertising" },
  { label: "Aerospace", value: "Aerospace" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Automotive", value: "Automotive" },
  { label: "Banking", value: "Banking" },
  { label: "Biotechnology", value: "Biotechnology" },
  { label: "Chemicals", value: "Chemicals" },
  { label: "Construction", value: "Construction" },
  { label: "Consumer Goods", value: "Consumer Goods" },
  { label: "Education", value: "Education" },
  { label: "Energy", value: "Energy" },
  { label: "Engineering", value: "Engineering" },
  { label: "Entertainment", value: "Entertainment" },
  { label: "Environmental Services", value: "Environmental Services" },
  { label: "Fashion", value: "Fashion" },
  { label: "Finance", value: "Finance" },
  { label: "Food & Beverage", value: "Food & Beverage" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Hospitality", value: "Hospitality" },
  { label: "Information Technology", value: "Information Technology" },
  { label: "Insurance", value: "Insurance" },
  { label: "Legal Services", value: "Legal Services" },
  { label: "Logistics & Transportation", value: "Logistics & Transportation" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Marketing", value: "Marketing" },
  { label: "Media & Communications", value: "Media & Communications" },
  { label: "Mining", value: "Mining" },
  { label: "Pharmaceuticals", value: "Pharmaceuticals" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Retail", value: "Retail" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Video Games", value: "Video Games" },
  { label: "Other", value: "Other" },
];

// currency
export const CURRENCY_TYPE = [
  { label: "USD - US Dollar ($)", value: "USD" },
  { label: "CAD - Canadian Dollar (CA$)", value: "CAD" },
  { label: "GBP - British Pound (£)", value: "GBP" },
  { label: "EUR - Euro (€)", value: "EUR" },
  { label: "AUD - Australian Dollar (A$)", value: "AUD" },
  { label: "JPY - Japanese Yen (¥)", value: "JPY" },
  { label: "CNY - Chinese Yuan (¥)", value: "CNY" },
  { label: "INR - Indian Rupee (₹)", value: "INR" },
  { label: "CHF - Swiss Franc (CHF)", value: "CHF" },
  { label: "NZD - New Zealand Dollar (NZ$)", value: "NZD" },
  { label: "SGD - Singapore Dollar (S$)", value: "SGD" },
  { label: "MXN - Mexican Peso (MX$)", value: "MXN" },
  { label: "BRL - Brazilian Real (R$)", value: "BRL" },
  { label: "ZAR - South African Rand (R)", value: "ZAR" },
  { label: "KRW - South Korean Won (₩)", value: "KRW" },
  { label: "Other", value: "Other" },
];

// Full menu items with icon
export const SETTINGS_ITEM = [
  {
    id: "organization profile",
    label: "Organization profile",
    icon: Building2,
  },
  { id: "Appearance", label: "Appearance", icon: Palette },
  { id: "Users", label: "Users", icon: Users },
  { id: "roles", label: "Roles", icon: User },
  { id: "taxes", label: "Taxes", icon: FileDigit },
  { id: "direct-taxes", label: "Direct Taxes", icon: File },
  { id: "customer-portal", label: "Customer Portal", icon: UserCheck },
  { id: "customers", label: "Customers", icon: UserCheck },
  { id: "quotes", label: "Quotes", icon: FileText },
  { id: "invoices", label: "Invoices", icon: File },
  { id: "expenses", label: "Expenses", icon: DollarSign },
  { id: "email-notification", label: "Email Notification", icon: Mail },
];
