export const INDUSTRY_TYPES = [
  { label: "Accounting", value: "Accounting" },
  { label: "Advertising", value: "Advertising" },
  { label: "Aerospace", value: "Aerospace" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Automotive", value: "Automotive" },
  { label: "Banking", value: "Banking" },
  { label: "Biotechnology", value: "Biotechnology" },
  { label: "Chemicals", value: "Chemicals" },
  { label: "Construction", value: "Construction" },
  { label: "Consumer Goods", value: "Consumer Goods" },
  { label: "Education", value: "Education" },
  { label: "Energy", value: "Energy" },
  { label: "Engineering", value: "Engineering" },
  { label: "Entertainment", value: "Entertainment" },
  { label: "Environmental Services", value: "Environmental Services" },
  { label: "Fashion", value: "Fashion" },
  { label: "Finance", value: "Finance" },
  { label: "Food & Beverage", value: "Food & Beverage" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Hospitality", value: "Hospitality" },
  { label: "Information Technology", value: "Information Technology" },
  { label: "Insurance", value: "Insurance" },
  { label: "Legal Services", value: "Legal Services" },
  { label: "Logistics & Transportation", value: "Logistics & Transportation" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Marketing", value: "Marketing" },
  { label: "Media & Communications", value: "Media & Communications" },
  { label: "Mining", value: "Mining" },
  { label: "Pharmaceuticals", value: "Pharmaceuticals" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Retail", value: "Retail" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Video Games", value: "Video Games" },
  { label: "Other", value: "Other" },
];

// Currency types
export const CURRENCY_TYPE = [
  { label: "USD", value: "USD" },
  { label: "CAD", value: "CAD" },
  { label: "GBP", value: "GBP" },
  { label: "EUR", value: "EUR" },
  { label: "AUD", value: "AUD" },
  { label: "JPY", value: "JPY" },
  { label: "CNY", value: "CNY" },
  { label: "INR", value: "INR" },
  { label: "CHF", value: "CHF" },
  { label: "NZD", value: "NZD" },
  { label: "SGD", value: "SGD" },
  { label: "MXN", value: "MXN" },
  { label: "BRL", value: "BRL" },
  { label: "ZAR", value: "ZAR" },
  { label: "Other", value: "Other" },
];
