import type { Metadata } from "next";
import { Mona_Sans as FontSans, Syncopate } from "next/font/google";
import { cn } from "@/utils/index";
import "@/styles/globals.css";
import ThemeProvider from "@/providers/theme-provider";
import ReactQueryProvider from "@/providers/react-query";
import BprogressProvider from "@/providers/bprogress";
export const fontSans = FontSans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-sans",
});

export const fontSyncopate = Syncopate({
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-syncopate",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans.variable,
          fontSyncopate.variable
        )}
      >
        <BprogressProvider>
          <ReactQueryProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ReactQueryProvider>
        </BprogressProvider>
      </body>
    </html>
  );
}
